### PR TITLE
Implement new design, coming soon page

### PR DESCRIPTION
**Pull request by headquarter8302**
Since I've been given owner privileges on the organisation, and the domain is only used as a redirect. It would be beneficial to give it some kind of refurbish and perhaps create a sort of "portal", a secondary website front for the wiki with much prettier looks free of FANDOM's restrictions and no ads.

I'm asking for feedback on the current state of the site, it is live for review on the [`newdesign` branch](Wikitubia/wikitubia.github.io/tree/newdesign) until merged to main. _This is currently a placeholder for future projects and/or website on the domain._

### CODE REVIEW

**Comment by Saurmandal** [comment]
Looks good! I was expecting more of a static site thing but this is okay too. Text could use a better colour scheme.

**Comment by headquarter8302** [comment]
Fixed light background returning 404 image because the URL for it is just so slightly different. 1f22f8139f74ad0f0dab665faa5439cdf2432331


> Looks good! I was expecting more of a static site thing but this is okay too. Text could use a better colour scheme.

Can you describe the colour scheme you expected? I'm using Wikitubia's theme as a colour scheme, and inverting the link colours on light preference.
https://github.com/Wikitubia/wikitubia.github.io/blob/1f22f8139f74ad0f0dab665faa5439cdf2432331/res/style.css#L86-L89

**Comment by Saurmandal** [comment]
My preference is set to dark, and I think it's now displaying correctly for other users except the page looks like this to me. It's failing to pull media from static.wikia.nocookie.net

image

**Comment by headquarter8302** [comment]
Yeah, should probably host those locally. Also, I discovered that the light theme background has significantly less resolution that the dark bg. I can probably upscale that but having the full-res thing is much better

**Pull request merged**
